config/routes.rb
Rails.application.routes.draw do
  root 'recommendations#index'
  resources :recommendations
  resources :searches

end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
	has_attached_file :image, styles: {large: "600x600>", medium: "300x300>", thumb: "150x150#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


	def self.search(search)
		if search
			where(["title LIKE ? OR category LIKE ? OR description LIKE ? OR location LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
		else
			all
		end
	end
end

app/models/search.rb
class Search < ActiveRecord::Base
	def search_recommendations
		recommendations = Recommendation.all
		recommendations = recommendations.where(["title LIKE ? OR category LIKE ? OR description LIKE ? OR location LIKE ?", "%#{keywords}%", "%#{keywords}%", "%#{keywords}%", "%#{keywords}%"]) unless keywords.blank?
		recommendations = recommendations.where(["category LIKE ?", category]) unless category.blank?
		recommendations = recommendations.where(["title LIKE ?", "%#{title}%"]) unless title.blank?
		recommendations = recommendations.where(["description LIKE ?", "%#{description}%"]) unless description.blank?
		recommendations = recommendations.where(["location LIKE ?", "%#{location}%"]) unless location.blank?

		return recommendations

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :set_recommendation, only: [:show, :edit, :update, :destroy]

  # GET /recommendations
  # GET /recommendations.json
  def index
    @recommendations = Recommendation.search(params[:search])
  end

  # GET /recommendations/1
  # GET /recommendations/1.json
  def show
  end

  # GET /recommendations/new
  def new
    @recommendation = Recommendation.new
  end

  # GET /recommendations/1/edit
  def edit
  end

  # POST /recommendations
  # POST /recommendations.json
  def create
    @recommendation = Recommendation.new(recommendation_params)

    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully created.' }
        format.json { render :show, status: :created, location: @recommendation }
      else
        format.html { render :new }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recommendations/1
  # PATCH/PUT /recommendations/1.json
  def update
    respond_to do |format|
      if @recommendation.update(recommendation_params)
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully updated.' }
        format.json { render :show, status: :ok, location: @recommendation }
      else
        format.html { render :edit }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations/1
  # DELETE /recommendations/1.json
  def destroy
    @recommendation.destroy
    respond_to do |format|
      format.html { redirect_to recommendations_url, notice: 'Recommendation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recommendation_params
      params.require(:recommendation).permit(:title, :location, :category, :description, :imageUrl, :image)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	def new
		@search = Search.new
		@categories = Recommendation.uniq.pluck(:category)
	end
	def create
		@search = Search.create(search_params)
		redirect_to @search
	end
	def show
		@search = Search.find(params[:id])
	end


	private

	def search_params
		params.require(:search).permit(:keywords, :category, :title, :description, :location)
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrekabillySearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recommendations/_form.html.erb
<%= form_for @recommendation, html: {multipart: true} do |f| %>
  <% if @recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
      <% @recommendation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :imageUrl %><br>
    <%= f.text_field :imageUrl %>
  </div>
    <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recommendations/edit.html.erb
<h1>Editing Recommendation</h1>

<%= render 'form' %>

<%= link_to 'Show', @recommendation %> |
<%= link_to 'Back', recommendations_path %>

app/views/recommendations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Local Spots Recommendations</h1>

<%= form_tag recommendations_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
<% end %>
<br>
<%= link_to "Advanced Search", new_search_path %>
<br><br>
<hr>
<table cellspacing="20">
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Category</th>
      <th>Description</th>
      <th>Imageurl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recommendations.each do |recommendation| %>
      <tr>
        <td><%= recommendation.title %></td>
        <td><%= recommendation.location %></td>
        <td><%= recommendation.category %></td>
        <td width="300"><%= recommendation.description %></td>

        <% if recommendation.image.file? %>
        <td> <%= image_tag recommendation.image.url(:medium) %></td>
        <% elsif recommendation.imageUrl.blank? %>
        <td><img src="http://i.imgur.com/Febvvif.png" height="200" width="300"></td>
        <% else %>
        <td><img src="<%= recommendation.imageUrl %>" height="200" width="300"></td>
        <% end %>


        <td><%= link_to 'Show', recommendation %></td>
        <td><%= link_to 'Edit', edit_recommendation_path(recommendation) %></td>
        <td><%= link_to 'Destroy', recommendation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recommendation', new_recommendation_path %>

app/views/recommendations/new.html.erb
<h1>New Recommendation</h1>

<%= render 'form' %>

<%= link_to 'Back', recommendations_path %>

app/views/recommendations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recommendation.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @recommendation.location %>
</p>

<p>
  <strong>Category:</strong>
  <%= @recommendation.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recommendation.description %>
</p>

  <% if @recommendation.image.file? %>
<p>
  <strong>Image Uploaded:</strong>
  <%= image_tag @recommendation.image.url(:medium) %>
</p>
  <% elsif @recommendation.imageUrl.blank? %>
<p>
  <strong>Imageurl:</strong>
  <img src="http://i.imgur.com/Febvvif.png">
</p>
<% else %>
<p>
  <strong>Imageurl:</strong>
  <img src="<%= @recommendation.imageUrl %>" height="200" width="300">
</p>
  <% end %>




<%= link_to 'Edit', edit_recommendation_path(@recommendation) %> |
<%= link_to 'Back', recommendations_path %>

app/views/searches/new.html.erb
<h1> Advanced Search</h1>
<%= form_for @search do |s| %>

	<div class="field">
		<%= s.label :keywords %> <br />
		<%= s.text_field :keywords %>
	</div>

	<div class="field">
		<%= s.label :category %> <br />
		<%= s.select :category, options_for_select(@categories), :include_blank => true %>
	</div>

	<div class="field">
		<%= s.label :title %> <br />
		<%= s.text_field :title %>
	</div>

	<div class="field">
		<%= s.label :description %> <br />
		<%= s.text_field :description %>
	</div>

	<div class="field">
		<%= s.label :location %> <br />
		<%= s.text_field :location %>
	</div>

	<div class="actions">
		<%= s.submit "Search" %>
	</div>
	<% end %>

	<p><%= link_to "Back", recommendations_path %></p>

app/views/searches/show.html.erb
<h1> Search Results</h1>

<% if @search.search_recommendations.empty? %>
	<p> Sorry, no results </p>
<% else %>
	<% @search.search_recommendations.each do |s| %>
	<br>

	<div class="results"> 
		<h4> Title: <%= s.title %></h4>
		<p> Category: <%= s.category %></p>
		<p> Description: <%= s.description %></p>
		<img src="<%= s.imageUrl%>" height="300" width="300">
	</div>

	<% end %>
<% end %>

<p><%= link_to "Back", new_search_path %></p>